version: '3'

networks:
  leaderboard-network:
    name: Leaderboard.Network
    driver: bridge

services:
  postgres:
    container_name: Leaderboard.Database
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: Leaderboard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 6432:5432
    networks:
      - leaderboard-network

  web:
    container_name: Leadboard.Api
    build: .
    restart: always
    env_file:
      - .env.docker
    ports:
      - 3000:3000
    networks:
      - leaderboard-network
    depends_on:
      - postgres
